// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0z-D-UqiFfg0D0cgdBeLATY1dc-x8SZY',
    appId: '1:69146413472:web:de8923d39331e449ff3cc5',
    messagingSenderId: '69146413472',
    projectId: 'signin1-f3061',
    authDomain: 'signin1-f3061.firebaseapp.com',
    storageBucket: 'signin1-f3061.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJ1V_Dt1VC9gmICALNCfmsRM7dTmNSwo',
    appId: '1:69146413472:android:5101ad05df3cd1a1ff3cc5',
    messagingSenderId: '69146413472',
    projectId: 'signin1-f3061',
    storageBucket: 'signin1-f3061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhw_m2BN3r3h_rV9SRAyKVoFLu0Hz5lc',
    appId: '1:69146413472:ios:620e17c5b9f0d25fff3cc5',
    messagingSenderId: '69146413472',
    projectId: 'signin1-f3061',
    storageBucket: 'signin1-f3061.firebasestorage.app',
    iosBundleId: 'com.example.googlesignin1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0z-D-UqiFfg0D0cgdBeLATY1dc-x8SZY',
    appId: '1:69146413472:web:394487dad35ad048ff3cc5',
    messagingSenderId: '69146413472',
    projectId: 'signin1-f3061',
    authDomain: 'signin1-f3061.firebaseapp.com',
    storageBucket: 'signin1-f3061.firebasestorage.app',
  );
}
